# Generated by Django 5.1.1 on 2024-10-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1)),
                ('zip_code', models.CharField(max_length=10)),
                ('town', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_state', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('TRES_BON_ETAT', 'Très bon état'), ('BON_ETAT', 'Bon état'), ('ETAT_CORRECT', 'État correct'), ('ENDOMMAGE', 'Endommagé'), ('INUTILISABLE', 'Inutilisable')], max_length=50)),
                ('arival_state', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('TRES_BON_ETAT', 'Très bon état'), ('BON_ETAT', 'Bon état'), ('ETAT_CORRECT', 'État correct'), ('ENDOMMAGE', 'Endommagé'), ('INUTILISABLE', 'Inutilisable')], max_length=50)),
                ('weight', models.FloatField()),
                ('fragile', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feelback.customer')),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feelback.deliverer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feelback.package')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delays_rate', models.IntegerField()),
                ('state_rate', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('TRES_BON_ETAT', 'Très bon état'), ('BON_ETAT', 'Bon état'), ('ETAT_CORRECT', 'État correct'), ('ENDOMMAGE', 'Endommagé'), ('INUTILISABLE', 'Inutilisable')], max_length=50)),
                ('behaviour_rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feelback.delivery')),
            ],
        ),
    ]
